/** @type {import('tailwindcss').Config} */
// Design tokens ported verbatim from the Stitch "Mindful Habit Tracker" export.
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'surface-bright': '#f9f9ff',
        surface: '#f9f9ff',
        'inverse-primary': '#4de082',
        'error-container': '#ffdad6',
        'secondary-fixed': '#d8e2ff',
        'on-tertiary-fixed-variant': '#653e00',
        'surface-tint': '#006d36',
        'on-primary-container': '#005e2d',
        outline: '#6d7b6d',
        'secondary-fixed-dim': '#adc6ff',
        'surface-container-low': '#f0f3ff',
        'primary-fixed-dim': '#4de082',
        'on-background': '#111c2d',
        'on-secondary-fixed': '#001a42',
        error: '#ba1a1a',
        'surface-dim': '#cfdaf2',
        'surface-container-lowest': '#ffffff',
        'secondary-container': '#2170e4',
        'surface-container-high': '#dee8ff',
        'on-primary-fixed-variant': '#005227',
        'tertiary-fixed-dim': '#ffb95f',
        background: '#f9f9ff',
        'on-error': '#ffffff',
        'primary-container': '#4ade80',
        'on-primary': '#ffffff',
        'on-secondary': '#ffffff',
        'primary-fixed': '#6dfe9c',
        'on-primary-fixed': '#00210c',
        'surface-container-highest': '#d8e3fb',
        'on-surface': '#111c2d',
        'tertiary-container': '#ffb657',
        secondary: '#0058be',
        'surface-variant': '#d8e3fb',
        'tertiary-fixed': '#ffddb8',
        'on-tertiary-container': '#734700',
        'on-secondary-fixed-variant': '#004395',
        'on-surface-variant': '#3d4a3e',
        'surface-container': '#e7eeff',
        'on-error-container': '#93000a',
        'inverse-surface': '#263143',
        'inverse-on-surface': '#ecf1ff',
        'on-tertiary': '#ffffff',
        tertiary: '#855300',
        primary: '#006d36',
        'on-secondary-container': '#fefcff',
        'on-tertiary-fixed': '#2a1700',
        'outline-variant': '#bccabb',
        // Dark-mode surface set (used under .dark)
        'dark-bg': '#0f1512',
        'dark-surface': '#171d1a',
        'dark-surface-container': '#1e2521',
        'dark-surface-high': '#28312c',
        'dark-on-surface': '#e0e4df',
        'dark-on-surface-variant': '#a8b4ab',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        '2xl': '1.5rem',
        full: '9999px',
      },
      spacing: {
        gutter: '16px',
        lg: '24px',
        md: '16px',
        'margin-desktop': '48px',
        xs: '4px',
        xl: '32px',
        sm: '8px',
        base: '4px',
        'margin-mobile': '16px',
      },
      fontFamily: {
        sans: ['Geist', 'system-ui', 'sans-serif'],
        'body-lg': ['Geist'],
        'label-md': ['Geist'],
        'headline-md': ['Geist'],
        'body-md': ['Geist'],
        'label-sm': ['Geist'],
        'headline-xl': ['Geist'],
        'headline-lg-mobile': ['Geist'],
        'headline-lg': ['Geist'],
      },
      fontSize: {
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '500' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px', fontWeight: '600' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
}
